version: 2
updates:
  # Enable version updates for npm (pnpm workspaces)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "bejarcode"
    assignees:
      - "bejarcode"
    # Group minor and patch updates together
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "tonal"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "ci/cd"
      - "dependencies"
      - "automated"
